### ISSUE TITLE
test_slicker.AliasTest.test_auto_with_conflicting_imports is flaky

### ISSUE THREAD

**Issue by benjaminjkraft** [Khan/slicker#18]

**Comment by benjaminjkraft** [comment]
This seems to happen consistently the first time I run tests after having modified slicker.py, and only running from the repo root (e.g. `python -m unittest discover tests`), not with `cd tests ; PYTHONPATH=.. python -m unittest discover` or similar.

**Comment by benjaminjkraft** [comment]
Except, apparently not every time, only most of the time.  I'm not totally sure why.  Here's the failure:
```
======================================================================
FAIL: test_auto_with_conflicting_imports (test_slicker.AliasTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/benkraft/khan/slicker/tests/test_slicker.py", line 1223, in test_auto_with_conflicting_imports
    new_extra_text='def foo():\n  from baz import bang')
  File "/home/benkraft/khan/slicker/tests/test_slicker.py", line 1154, in assert_
    self.assertMultiLineEqual(expected, actual)
AssertionError: 'from baz import bang\n\nX = bang.X\ndef foo():\n  from baz import bang\n' != 'import baz.bang\n\nX = baz.bang.X\ndef foo():\n  import baz.bang\n'
- from baz import bang
+ import baz.bang
  
- X = bang.X
+ X = baz.bang.X
?     ++++
  def foo():
-   from baz import bang
+   import baz.bang
```
